# uses C behind the scenes
language: c

# only build the default `github` branch
branches:
  only:
  - master

# make builds on `bionic` ubuntu images
# on both `amd64` and `arm64` architectures
jobs:
  include:
    - name: Bionic Build amd64
      os: linux
      dist: bionic
      arch: amd64
      script: bash ./travis/build_linux.sh "rue-generic-$TRAVIS_OS_NAME-$TRAVIS_CPU_ARCH-build_$TRAVIS_BUILD_NUMBER.zip"
      env: RUE_BUILD_NAME="generic"
    - name: Bionic Build amd64 - Steam
      os: linux
      dist: bionic
      arch: amd64
      script: bash ./travis/build_linux_steam.sh "rue-steam-$TRAVIS_OS_NAME-$TRAVIS_CPU_ARCH-build_$TRAVIS_BUILD_NUMBER.zip"
      env: RUE_BUILD_NAME="steam"
    - name: Bionic Build arm64
      os: linux
      dist: bionic
      arch: arm64
      script: bash ./travis/build_linux.sh "rue-generic-$TRAVIS_OS_NAME-$TRAVIS_CPU_ARCH-build_$TRAVIS_BUILD_NUMBER.zip"
      env: RUE_BUILD_NAME="generic"
    - name: Windows
      os: windows
      script: bash ./travis/build_windows.sh "rue-generic-$TRAVIS_OS_NAME-$TRAVIS_CPU_ARCH-build_$TRAVIS_BUILD_NUMBER.zip"
      env: RUE_BUILD_NAME="generic"
     - name: Windows - Steam
       os: windows
       script: bash ./travis/build_windows_steam.sh "rue-steam-$TRAVIS_OS_NAME-$TRAVIS_CPU_ARCH-build_$TRAVIS_BUILD_NUMBER.zip"
       env: RUE_BUILD_NAME="steam"

# install dependencies
addons:
  apt:
    packages:
      - git
      - make
      - zip
      - ca-certificates

      # glew dependencies
      - build-essential
      - libxmu-dev
      - libxi-dev
      - libgl-dev

      # SDL & SDL_mixer dependencies
      - build-essential
      - git
      - make
      - cmake
      - autoconf
      - automake
      - libtool
      - pkg-config
      - libasound2-dev
      - libpulse-dev
      - libaudio-dev
      - libjack-dev
      - libx11-dev
      - libxext-dev
      - libxrandr-dev
      - libxcursor-dev
      - libxfixes-dev
      - libxi-dev
      - libxss-dev
      - libgl1-mesa-dev
      - libdbus-1-dev
      - libudev-dev
      - libgles2-mesa-dev
      - libegl1-mesa-dev
      - libibus-1.0-dev
      - fcitx-libs-dev
      - libsamplerate0-dev
      - libsndio-dev
      - libwayland-dev
      - libxkbcommon-dev
      - libdrm-dev
      - libgbm-dev

      # read opus files
      - libopusfile-dev

      # opus
      - libssl-dev

deploy:
  provider: releases
  api_key: "$GITHUB_DEPLOY_RUE"
  file: "rue-$RUE_BUILD_NAME-$TRAVIS_OS_NAME-$TRAVIS_CPU_ARCH-build_$TRAVIS_BUILD_NUMBER.zip"
  skip_cleanup: true
  draft: true
  #on:
  #  tags: true
