set(SDL2_INCLUDE_DIRS "${CMAKE_CURRENT_LIST_DIR}/include")

if (${CMAKE_SIZEOF_VOID_P} MATCHES 8)
	set(SDL2_LIBRARIES "${CMAKE_CURRENT_LIST_DIR}/lib/x64/SDL2.lib;${CMAKE_CURRENT_LIST_DIR}/lib/x64/SDL2main.lib")
	install(FILES "${CMAKE_CURRENT_LIST_DIR}/lib/x64/SDL2.dll" DESTINATION bin/)
else ()
	set(SDL2_LIBRARIES "${CMAKE_CURRENT_LIST_DIR}/lib/x86/SDL2.lib;${CMAKE_CURRENT_LIST_DIR}/lib/x86/SDL2main.lib")
	install(FILES "${CMAKE_CURRENT_LIST_DIR}/lib/x86/SDL2.dll" DESTINATION bin/)
endif ()

string(STRIP "${SDL2_LIBRARIES}" SDL2_LIBRARIES)
