set(SDL2_MIXER_INCLUDE_DIRS "${CMAKE_CURRENT_LIST_DIR}/include")

if (${CMAKE_SIZEOF_VOID_P} MATCHES 8)
	set(SDL2_MIXER_LIBRARIES "${CMAKE_CURRENT_LIST_DIR}/lib/x64/SDL2_mixer.lib")
	install(FILES "${CMAKE_CURRENT_LIST_DIR}/lib/x64/SDL2_mixer.dll" DESTINATION bin/)
else ()
	set(SDL2_MIXER_LIBRARIES "${CMAKE_CURRENT_LIST_DIR}/lib/x86/SDL2_mixer.lib")
	install(FILES "${CMAKE_CURRENT_LIST_DIR}/lib/x86/SDL2_mixer.dll" DESTINATION bin/)
endif ()

string(STRIP "${SDL2_MIXER_LIBRARIES}" SDL2_MIXER_LIBRARIES)
