name: Auto build

on:
  push:
    branches:
      - feature/reuse_github_workflows

jobs:
  call-workflow-in-another-repo:
    uses: tomtsagk/avdl/.github/workflows/.compile_avdl_project.yml@d4d4dca2c0642cc684001f779eec7ef85d26d3cc
    with:
        project_name: rue
