name: Auto build

on:
  push:
    branches:
      - feature/reuse_github_workflows

jobs:
  avdl:
    uses: tomtsagk/avdl/.github/workflows/.compile_avdl_project.yml@70355d355b5424ee0f1ae5321f53c905a65b4243
    with:
        project_name: rue
        build_android: true
        build_android_googleplay: false
        build_ads: false
        build_steam: false
        build_linux: false
        build_windows: false
        build_quest2: false
        build_quest2_oculus: false
