name: Build Project

on:
  push:
    branches:
      - master
      - develop
    tags:
      "v[0-9]+.[0-9]+.[0-9]+*"

jobs:
  avdl:
    uses: tomtsagk/avdl/.github/workflows/.compile_avdl_project.yml@65a808e63804c6ede533b163a587cf651619d414
    with:
        project_name: rue
        build_android: true
        build_android_googleplay: true
        build_ads: false
        build_steam: true
        build_linux: true
        build_windows: true
        build_quest2: true
        build_quest2_oculus: true
        itchio_user: afloofdev
        itchio_project: rue
        oculus_channel: store
    secrets:
        # required for android
        ANDROID_KEYSTORE: ${{ secrets.KEYSTORE }}
        ANDROID_KEYSTORE_PASSWORD: ${{ secrets.KEYSTORE_PASSWORD }}
        # required for itchio release
        BUTLER_API_KEY: ${{ secrets.BUTLER_API_KEY }}
        # required for oculus
        OCULUS_API_LINK: ${{ secrets.OCULUS_API_LINK }}
        OCULUS_PROJECT_ID: ${{ secrets.OCULUS_PROJECT_ID }}
        # required for google play
        GOOGLE_PLAY_ID: ${{ secrets.GOOGLE_PLAY_ID }}
        AVDL_GOOGLE_PLAY_ACHIEVEMENTS: --google-play-achievement "ACHIEVEMENT_ROSE_SELECTED" ${{ secrets.ACHIEVEMENT_ROSE_SELECTED }} --google-play-achievement "ACHIEVEMENT_EXTRA_DISCARD" ${{ secrets.ACHIEVEMENT_EXTRA_DISCARD }} --google-play-achievement "ACHIEVEMENT_I_FOUND_THE_ROSE" ${{ secrets.ACHIEVEMENT_I_FOUND_THE_ROSE }} --google-play-achievement "ACHIEVEMENT_FIRST_VICTORY" ${{ secrets.ACHIEVEMENT_FIRST_VICTORY }} --google-play-achievement "ACHIEVEMENT_GETTING_BETTER" ${{ secrets.ACHIEVEMENT_GETTING_BETTER }} --google-play-achievement "ACHIEVEMENT_MASTER_PLAYER" ${{ secrets.ACHIEVEMENT_MASTER_PLAYER }}
        #ADMOB_PROJECT_ID: ${{ secrets.ADMOB_PROJECT_ID }}
        #ADMOB_INTERSTITIAL_AD_ID: ${{ secrets.ADMOB_INTERSTITIAL_AD_ID }}
        STEAMWORKS_APPID: ${{ secrets.STEAMWORKS_APPID }}
        STEAMWORKS_DEPOTID_LINUX: ${{ secrets.STEAMWORKS_DEPOTID_LINUX }}
        STEAMWORKS_DEPOTID_WINDOWS: ${{ secrets.STEAMWORKS_DEPOTID_WINDOWS }}
        STEAMWORKS_USERNAME: ${{ secrets.STEAMWORKS_USERNAME }}
        STEAMWORKS_TOKEN: ${{ secrets.STEAMWORKS_TOKEN }}
        # oculus release
        OCULUS_APPID: ${{ secrets.OCULUS_APPID }}
        OCULUS_APPSECRET: ${{ secrets.OCULUS_APPSECRET }}
        OCULUS_CLI_URL: ${{ secrets.OCULUS_CLI_URL }}
