name: Auto build

on:
  push:
    branches:
      - feature/reuse_github_workflows

jobs:
  avdl:
    uses: tomtsagk/avdl/.github/workflows/.compile_avdl_project.yml@16c72c72afdffb21f1d5be8d6b3fd66d637f8673
    with:
        project_name: rue
        build_android: true
        build_android_googleplay: false
        build_ads: true
        build_steam: false
        build_linux: false
        build_windows: false
        build_quest2: false
        build_quest2_oculus: false
    secrets:
        ANDROID_KEYSTORE: ${{ secrets.KEYSTORE }}
        ANDROID_KEYSTORE_PASSWORD: ${{ secrets.KEYSTORE_PASSWORD }}
