name: Auto build

on:
  push:
    branches:
      - feature/reuse_github_workflows

jobs:
  avdl:
    uses: tomtsagk/avdl/.github/workflows/.compile_avdl_project.yml@70a13d0c2f3e716a0486eb4f0f4a42c29e6e3b42
    with:
        project_name: rue
        build_android: false
        build_android_googleplay: false
        build_ads: false
        build_steam: false
        build_linux: false
        build_windows: false
        build_quest2: true
        build_quest2_oculus: true
    secrets:
        # required for android
        ANDROID_KEYSTORE: ${{ secrets.KEYSTORE }}
        ANDROID_KEYSTORE_PASSWORD: ${{ secrets.KEYSTORE_PASSWORD }}
        OCULUS_API_LINK: ${{ secrets.OCULUS_API_LINK }}
        OCULUS_PROJECT_ID: ${{ secrets.OCULUS_PROJECT_ID }}
        #ADMOB_PROJECT_ID: ${{ secrets.ADMOB_PROJECT_ID }}
        #ADMOB_INTERSTITIAL_AD_ID: ${{ secrets.ADMOB_INTERSTITIAL_AD_ID }}
