name: Auto build

on:
  push:
    branches:
      - feature/reuse_github_workflows

jobs:
  avdl:
    uses: tomtsagk/avdl/.github/workflows/.compile_avdl_project.yml@4402956f9f8dc48f39c76baaed9a5eb518892c48
    with:
        project_name: rue
        build_android: true
        build_android_googleplay: false
        build_ads: false
        build_steam: false
        build_linux: false
        build_windows: false
        build_quest2: false
        build_quest2_oculus: false
    secrets:
        KEYSTORE: ${{ secrets.KEYSTORE }}
        KEYSTORE_PASSWORD: ${{ secrets.KEYSTORE_PASSWORD }}
